[profile.default]
src = "src"
out = "out"
libs = ["lib"]

evm_version = "cancun"
remappings = [
    "~=src/"
]
ignored_error_codes = [5159, 3860, 2394, 5574]

[invariant]
fail_on_revert=true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config