[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
evm_version = "cancun"
remappings = [
    "~=src/"
]
ignored_error_codes = [5159, 3860, 2394, 5574, 2018]

[invariant]
fail_on_revert=true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

